# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/moisture.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/moisture.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14proto/moisture.proto\"\"\n\x0fMoistureRequest\x12\x0f\n\x07plantId\x18\x01 \x01(\x05\"P\n\x08Moisture\x12\x0f\n\x07plantId\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x63reated\x18\x04 \x01(\t\"5\n\x15MoistureArrayResponse\x12\x1c\n\tmoistures\x18\x01 \x03(\x0b\x32\t.Moisture2J\n\x0cMoistureData\x12:\n\x0cGetMoistures\x12\x10.MoistureRequest\x1a\x16.MoistureArrayResponse\"\x00\x62\x06proto3'
)




_MOISTUREREQUEST = _descriptor.Descriptor(
  name='MoistureRequest',
  full_name='MoistureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plantId', full_name='MoistureRequest.plantId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=58,
)


_MOISTURE = _descriptor.Descriptor(
  name='Moisture',
  full_name='Moisture',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plantId', full_name='Moisture.plantId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Moisture.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Moisture.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='Moisture.created', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=60,
  serialized_end=140,
)


_MOISTUREARRAYRESPONSE = _descriptor.Descriptor(
  name='MoistureArrayResponse',
  full_name='MoistureArrayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='moistures', full_name='MoistureArrayResponse.moistures', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=195,
)

_MOISTUREARRAYRESPONSE.fields_by_name['moistures'].message_type = _MOISTURE
DESCRIPTOR.message_types_by_name['MoistureRequest'] = _MOISTUREREQUEST
DESCRIPTOR.message_types_by_name['Moisture'] = _MOISTURE
DESCRIPTOR.message_types_by_name['MoistureArrayResponse'] = _MOISTUREARRAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MoistureRequest = _reflection.GeneratedProtocolMessageType('MoistureRequest', (_message.Message,), {
  'DESCRIPTOR' : _MOISTUREREQUEST,
  '__module__' : 'proto.moisture_pb2'
  # @@protoc_insertion_point(class_scope:MoistureRequest)
  })
_sym_db.RegisterMessage(MoistureRequest)

Moisture = _reflection.GeneratedProtocolMessageType('Moisture', (_message.Message,), {
  'DESCRIPTOR' : _MOISTURE,
  '__module__' : 'proto.moisture_pb2'
  # @@protoc_insertion_point(class_scope:Moisture)
  })
_sym_db.RegisterMessage(Moisture)

MoistureArrayResponse = _reflection.GeneratedProtocolMessageType('MoistureArrayResponse', (_message.Message,), {
  'DESCRIPTOR' : _MOISTUREARRAYRESPONSE,
  '__module__' : 'proto.moisture_pb2'
  # @@protoc_insertion_point(class_scope:MoistureArrayResponse)
  })
_sym_db.RegisterMessage(MoistureArrayResponse)



_MOISTUREDATA = _descriptor.ServiceDescriptor(
  name='MoistureData',
  full_name='MoistureData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=197,
  serialized_end=271,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetMoistures',
    full_name='MoistureData.GetMoistures',
    index=0,
    containing_service=None,
    input_type=_MOISTUREREQUEST,
    output_type=_MOISTUREARRAYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MOISTUREDATA)

DESCRIPTOR.services_by_name['MoistureData'] = _MOISTUREDATA

# @@protoc_insertion_point(module_scope)
