# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/plant.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/plant.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11proto/plant.proto\"r\n\x05Plant\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nwaterValue\x18\x04 \x01(\x05\x12\x15\n\rmoistureValue\x18\x05 \x01(\x02\x12\x0f\n\x07\x63reated\x18\x06 \x01(\t\"F\n\rPlantResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x15\n\x05plant\x18\x03 \x01(\x0b\x32\x06.Plant\"7\n\x12UpdatePlantRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\x05plant\x18\x02 \x01(\x0b\x32\x06.Plant\"\x0e\n\x0c\x45mptyRequest\",\n\x12PlantArrayResponse\x12\x16\n\x06plants\x18\x01 \x03(\x0b\x32\x06.Plant2\x9d\x01\n\tPlantData\x12\'\n\x0b\x43reatePlant\x12\x06.Plant\x1a\x0e.PlantResponse\"\x00\x12\x34\n\x0bUpdatePlant\x12\x13.UpdatePlantRequest\x1a\x0e.PlantResponse\"\x00\x12\x31\n\tGetPlants\x12\r.EmptyRequest\x1a\x13.PlantArrayResponse\"\x00\x62\x06proto3'
)




_PLANT = _descriptor.Descriptor(
  name='Plant',
  full_name='Plant',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Plant.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='Plant.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Plant.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waterValue', full_name='Plant.waterValue', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moistureValue', full_name='Plant.moistureValue', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='Plant.created', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=135,
)


_PLANTRESPONSE = _descriptor.Descriptor(
  name='PlantResponse',
  full_name='PlantResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='PlantResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='PlantResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plant', full_name='PlantResponse.plant', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=207,
)


_UPDATEPLANTREQUEST = _descriptor.Descriptor(
  name='UpdatePlantRequest',
  full_name='UpdatePlantRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='UpdatePlantRequest.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plant', full_name='UpdatePlantRequest.plant', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=264,
)


_EMPTYREQUEST = _descriptor.Descriptor(
  name='EmptyRequest',
  full_name='EmptyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=280,
)


_PLANTARRAYRESPONSE = _descriptor.Descriptor(
  name='PlantArrayResponse',
  full_name='PlantArrayResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plants', full_name='PlantArrayResponse.plants', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=326,
)

_PLANTRESPONSE.fields_by_name['plant'].message_type = _PLANT
_UPDATEPLANTREQUEST.fields_by_name['plant'].message_type = _PLANT
_PLANTARRAYRESPONSE.fields_by_name['plants'].message_type = _PLANT
DESCRIPTOR.message_types_by_name['Plant'] = _PLANT
DESCRIPTOR.message_types_by_name['PlantResponse'] = _PLANTRESPONSE
DESCRIPTOR.message_types_by_name['UpdatePlantRequest'] = _UPDATEPLANTREQUEST
DESCRIPTOR.message_types_by_name['EmptyRequest'] = _EMPTYREQUEST
DESCRIPTOR.message_types_by_name['PlantArrayResponse'] = _PLANTARRAYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Plant = _reflection.GeneratedProtocolMessageType('Plant', (_message.Message,), {
  'DESCRIPTOR' : _PLANT,
  '__module__' : 'proto.plant_pb2'
  # @@protoc_insertion_point(class_scope:Plant)
  })
_sym_db.RegisterMessage(Plant)

PlantResponse = _reflection.GeneratedProtocolMessageType('PlantResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLANTRESPONSE,
  '__module__' : 'proto.plant_pb2'
  # @@protoc_insertion_point(class_scope:PlantResponse)
  })
_sym_db.RegisterMessage(PlantResponse)

UpdatePlantRequest = _reflection.GeneratedProtocolMessageType('UpdatePlantRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEPLANTREQUEST,
  '__module__' : 'proto.plant_pb2'
  # @@protoc_insertion_point(class_scope:UpdatePlantRequest)
  })
_sym_db.RegisterMessage(UpdatePlantRequest)

EmptyRequest = _reflection.GeneratedProtocolMessageType('EmptyRequest', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYREQUEST,
  '__module__' : 'proto.plant_pb2'
  # @@protoc_insertion_point(class_scope:EmptyRequest)
  })
_sym_db.RegisterMessage(EmptyRequest)

PlantArrayResponse = _reflection.GeneratedProtocolMessageType('PlantArrayResponse', (_message.Message,), {
  'DESCRIPTOR' : _PLANTARRAYRESPONSE,
  '__module__' : 'proto.plant_pb2'
  # @@protoc_insertion_point(class_scope:PlantArrayResponse)
  })
_sym_db.RegisterMessage(PlantArrayResponse)



_PLANTDATA = _descriptor.ServiceDescriptor(
  name='PlantData',
  full_name='PlantData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=329,
  serialized_end=486,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreatePlant',
    full_name='PlantData.CreatePlant',
    index=0,
    containing_service=None,
    input_type=_PLANT,
    output_type=_PLANTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='UpdatePlant',
    full_name='PlantData.UpdatePlant',
    index=1,
    containing_service=None,
    input_type=_UPDATEPLANTREQUEST,
    output_type=_PLANTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetPlants',
    full_name='PlantData.GetPlants',
    index=2,
    containing_service=None,
    input_type=_EMPTYREQUEST,
    output_type=_PLANTARRAYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLANTDATA)

DESCRIPTOR.services_by_name['PlantData'] = _PLANTDATA

# @@protoc_insertion_point(module_scope)
