# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/water.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/water.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11proto/water.proto\"6\n\x0fWateringRequest\x12\x0f\n\x07plantId\x18\x01 \x01(\x05\x12\x12\n\nwaterValue\x18\x02 \x01(\x05\"\x0f\n\rEmptyResponse\"\"\n\x0fGetWaterRequest\x12\x0f\n\x07plantId\x18\x01 \x01(\x05\"M\n\x05Water\x12\x0f\n\x07plantId\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0f\n\x07\x63reated\x18\x04 \x01(\t\"\'\n\rWaterResponse\x12\x16\n\x06waters\x18\x01 \x03(\x0b\x32\x06.Water2k\n\tWaterData\x12.\n\x08SetWater\x12\x10.WateringRequest\x1a\x0e.EmptyResponse\"\x00\x12.\n\x08GetWater\x12\x10.GetWaterRequest\x1a\x0e.WaterResponse\"\x00\x62\x06proto3'
)




_WATERINGREQUEST = _descriptor.Descriptor(
  name='WateringRequest',
  full_name='WateringRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plantId', full_name='WateringRequest.plantId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='waterValue', full_name='WateringRequest.waterValue', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=75,
)


_EMPTYRESPONSE = _descriptor.Descriptor(
  name='EmptyResponse',
  full_name='EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=92,
)


_GETWATERREQUEST = _descriptor.Descriptor(
  name='GetWaterRequest',
  full_name='GetWaterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plantId', full_name='GetWaterRequest.plantId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=128,
)


_WATER = _descriptor.Descriptor(
  name='Water',
  full_name='Water',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='plantId', full_name='Water.plantId', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Water.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Water.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='created', full_name='Water.created', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=207,
)


_WATERRESPONSE = _descriptor.Descriptor(
  name='WaterResponse',
  full_name='WaterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='waters', full_name='WaterResponse.waters', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=248,
)

_WATERRESPONSE.fields_by_name['waters'].message_type = _WATER
DESCRIPTOR.message_types_by_name['WateringRequest'] = _WATERINGREQUEST
DESCRIPTOR.message_types_by_name['EmptyResponse'] = _EMPTYRESPONSE
DESCRIPTOR.message_types_by_name['GetWaterRequest'] = _GETWATERREQUEST
DESCRIPTOR.message_types_by_name['Water'] = _WATER
DESCRIPTOR.message_types_by_name['WaterResponse'] = _WATERRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WateringRequest = _reflection.GeneratedProtocolMessageType('WateringRequest', (_message.Message,), {
  'DESCRIPTOR' : _WATERINGREQUEST,
  '__module__' : 'proto.water_pb2'
  # @@protoc_insertion_point(class_scope:WateringRequest)
  })
_sym_db.RegisterMessage(WateringRequest)

EmptyResponse = _reflection.GeneratedProtocolMessageType('EmptyResponse', (_message.Message,), {
  'DESCRIPTOR' : _EMPTYRESPONSE,
  '__module__' : 'proto.water_pb2'
  # @@protoc_insertion_point(class_scope:EmptyResponse)
  })
_sym_db.RegisterMessage(EmptyResponse)

GetWaterRequest = _reflection.GeneratedProtocolMessageType('GetWaterRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETWATERREQUEST,
  '__module__' : 'proto.water_pb2'
  # @@protoc_insertion_point(class_scope:GetWaterRequest)
  })
_sym_db.RegisterMessage(GetWaterRequest)

Water = _reflection.GeneratedProtocolMessageType('Water', (_message.Message,), {
  'DESCRIPTOR' : _WATER,
  '__module__' : 'proto.water_pb2'
  # @@protoc_insertion_point(class_scope:Water)
  })
_sym_db.RegisterMessage(Water)

WaterResponse = _reflection.GeneratedProtocolMessageType('WaterResponse', (_message.Message,), {
  'DESCRIPTOR' : _WATERRESPONSE,
  '__module__' : 'proto.water_pb2'
  # @@protoc_insertion_point(class_scope:WaterResponse)
  })
_sym_db.RegisterMessage(WaterResponse)



_WATERDATA = _descriptor.ServiceDescriptor(
  name='WaterData',
  full_name='WaterData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=250,
  serialized_end=357,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetWater',
    full_name='WaterData.SetWater',
    index=0,
    containing_service=None,
    input_type=_WATERINGREQUEST,
    output_type=_EMPTYRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetWater',
    full_name='WaterData.GetWater',
    index=1,
    containing_service=None,
    input_type=_GETWATERREQUEST,
    output_type=_WATERRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WATERDATA)

DESCRIPTOR.services_by_name['WaterData'] = _WATERDATA

# @@protoc_insertion_point(module_scope)
